# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uxWqAzth5bED_uqojEhpu0Wkd3Miq0m
"""



"""# Parallel_Simulation_Cluster

"""

import os, math, time, multiprocessing as mp
import numpy as np
import rebound

# ---------------- user constants ----------------
M_A, L_A = 1.133, 1.519
M_B, abin, ebin = 0.972, 23.78, 0.52
omg_bin, MA_bin = np.radians(231.65 + 204.85), np.radians(209.6901)

M_E = 3.003e-6
R_E = 4.26352e-5
R_roche = 2.44 * R_E * (5.5 / 3.3)**(1./3)
ap = np.sqrt(L_A)  # planet semimajor axis
t_scale, out_step, num_particles = 1e4, 0.5, 10
output_root = "/content/drive/MyDrive/BatchRun"
os.makedirs(output_root, exist_ok=True)

# ---------------- utilities ----------------
def hill_radius(Ms, Mp, a): return a*(Mp/(3.*Ms))**(1./3.)
def get_MA(j): return (2.*math.pi*j*(1.+math.sqrt(5))/2.) % (2.*math.pi)
def safe_str(x): return f"{float(x):.10e}" if np.isfinite(x) else "nan"

def fallback_a_e(p, primary):
    try:
        rx, ry, rz = p.x-primary.x, p.y-primary.y, p.z-primary.z
        vx, vy, vz = p.vx-primary.vx, p.vy-primary.vy, p.vz-primary.vz
        r2 = rx**2 + ry**2 + rz**2
        if r2 <= 0: return float('nan'), float('nan')
        r, v2 = math.sqrt(r2), vx**2+vy**2+vz**2
        G, Mtot = 4.*math.pi**2, primary.m+p.m
        denom = 2./r - v2/(G*Mtot)
        if not np.isfinite(denom) or denom==0: return float('nan'), float('nan')
        a = 1./denom
        hx, hy, hz = ry*vz-rz*vy, rz*vx-rx*vz, rx*vy-ry*vx
        h2 = hx**2+hy**2+hz**2
        tmp = max(0, 1.-h2/(G*Mtot*a))
        return a, math.sqrt(tmp)
    except: return float('nan'), float('nan')

# ---------------- worker ----------------
def run_job(job):
    mass_earth, beta = job
    m_planet = mass_earth*M_E
    mass_folder = os.path.join(output_root, f"{int(mass_earth)}M_E")
    beta_folder = os.path.join(mass_folder, f"beta_{beta:.1f}")
    os.makedirs(beta_folder, exist_ok=True)

    # per-particle evolution files
    tp_files = [open(os.path.join(beta_folder, f"tp{j}_evolution.txt"), "a") for j in range(num_particles)]
    for fh in tp_files:
        fh.write("# time_yr,a_AU,e\n")

    res_path = os.path.join(beta_folder, "results.txt")
    with open(res_path, "a") as fh:
        fh.write("# planet_mass_EarthMass,beta,tp_index,a_tp_AU,period_ratio,lifetime_yr,log10_lifetime\n")

    # ---------------- simulation setup ----------------
    sim = rebound.Simulation()
    sim.units = ('AU','Msun','yr')
    sim.integrator = "ias15"
    sim.dt = 0.042
    sim.collision = "direct"

    sim.add(m=M_A)  # host star
    sim.add(m=m_planet, a=ap, M=get_MA(1), r=R_E, primary=sim.particles[0])
    R_H = hill_radius(M_A, m_planet, ap)

    # add test particles
    test_hashes = []
    for j in range(num_particles):
        sim.add(m=0, a=ap + beta*R_H, M=get_MA(2+j), r=R_E,
                primary=sim.particles[0], hash=f"tp{j}")
        test_hashes.append(f"tp{j}")

    sim.add(m=M_B, a=abin, e=ebin, omega=omg_bin, M=MA_bin)
    sim.move_to_com()

    # simulation archive
    archive_path = os.path.join(beta_folder, "archive.bin")
    try:
        sim.automateSimulationArchive(archive_path, interval=out_step, deletefile=False)
    except Exception:
        pass  # Not fatal; continue without archiving

    last_a = np.full(num_particles, np.nan)
    last_e = np.full(num_particles, np.nan)
    lifetime = np.full(num_particles, np.nan)
    ps_star = sim.particles[0]

    t = 0.0
    while t < t_scale:
        t_next = min(t + out_step, t_scale)
        try: sim.integrate(t_next)
        except: pass

        for idx, h in enumerate(test_hashes):
            try:
                p = sim.particles[h]
                a_val, e_val = fallback_a_e(p, ps_star)
                if np.isfinite(a_val): last_a[idx] = a_val
                if np.isfinite(e_val): last_e[idx] = e_val
                tp_files[idx].write(f"{sim.t:.8e},{safe_str(last_a[idx])},{safe_str(last_e[idx])}\n")
            except:
                tp_files[idx].write(f"{sim.t:.8e},{safe_str(last_a[idx])},{safe_str(last_e[idx])}\n")

            if np.isnan(lifetime[idx]):
                try:
                    dist = np.linalg.norm([p.x-sim.particles[1].x, p.y-sim.particles[1].y, p.z-sim.particles[1].z])
                    if p.d>8.0 or p.d<0.1 or dist<R_roche:
                        lifetime[idx] = sim.t
                        sim.remove(hash=h)
                except: lifetime[idx] = sim.t

        # Removed sa.add(sim) as automateSimulationArchive handles it.
        if np.all(~np.isnan(lifetime)): break
        t = t_next

    for fh in tp_files: fh.close()

    # write results
    a_initials = [ap + beta*R_H for _ in range(num_particles)]
    P_planet = math.sqrt(ap**3/M_A)
    P_particles = np.sqrt(np.array(a_initials)**3/M_A)
    with open(res_path,"a") as fh:
        for idx in range(num_particles):
            life = lifetime[idx] if not np.isnan(lifetime[idx]) else sim.t
            logt = math.log10(life) if life>0 else float('nan')
            fh.write(f"{mass_earth:.1f},{beta:.2f},{idx},{a_initials[idx]:.8e},{P_particles[idx]/P_planet:.8e},{life:.8e},{logt:.8e}\n")

    print(f"[done] {int(mass_earth)}M_E beta={beta:.1f} -> {beta_folder}")

# ---------------- main ----------------
if __name__=="__main__":
    planet_mass_factors = [100,200,300]
    beta_values = np.arange(2.0,30.5,0.5)
    jobs = [(m,float(b)) for m in planet_mass_factors for b in beta_values]
    nproc = min(mp.cpu_count(), len(jobs))
    t0 = time.time()
    with mp.Pool(processes=nproc) as pool:
        pool.map(run_job, jobs)
    print("All jobs finished in {:.2f} minutes".format((time.time()-t0)/60.0))